Sprint1 (Jan 19 - Feb 2)
ClevertecFrontendLab/sprint1-fstk1337 pull request #1
Opened 2023-01-29 15:37 UTC by fstk1337

2023-01-29 15:39 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 83.33333333333334%.
Общее количество тестов: 6.
Количество непройденных тестов: 1.
***
**Test width 320px -- test layout book-page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/fstk1337/1675006769/Test%20width%20320px%20--%20test%20layout%20book-page%20(failed).png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/fstk1337/1675006769/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/fstk1337/1675006769/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/fstk1337/1675006769/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/fstk1337/1675006769/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/fstk1337/1675006769/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/fstk1337/1675006769/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/fstk1337/1675006769/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/fstk1337/1675006769/content-window.png)

2023-01-29 16:19 UTC, dariavorom requested changes

2023-01-29 16:19 UTC, dariavorom commented on src/components/app-nav-categories/app-nav-categories.tsx
> +const categories = [
подобные константы ( с данными, переиспользуемые  в  других компонентах) - вынести в отдельную папку constants и в файлики. тем более такие большие загромождают компонент

2023-01-29 16:19 UTC, dariavorom commented on src/components/app-nav/app-nav.tsx
> +const navTabs = [
вынести

2023-01-29 16:19 UTC, dariavorom commented on src/components/book-list/book-list.tsx
> +const books = [
вынести

2023-01-29 16:19 UTC, dariavorom commented on src/components/book-main/book-main.tsx
> +const reviews = [
вынести

2023-01-29 16:19 UTC, dariavorom commented on src/pages/book/book-page.tsx
> +const books = [
вынести

2023-01-29 16:19 UTC, dariavorom commented on src/pages/public-offer/public-offer-content.tsx
> +export function PublicOfferContent() {
используй что-то одно. у тебя проскакивает где-то function declaration, больше arrow function.

2023-01-29 16:19 UTC, dariavorom commented on src/pages/book/book-page.tsx
> +import { useParams } from 'react-router-dom';
у тебя не проходит тест при клике на карточку книги, есть горизонтальный скролл, что-то с версткой где-то, не видна карточка полностью, на нее невозможно кликнуть. пересмотри, разберись 
![image](https://user-images.githubusercontent.com/64946271/215339712-fe6c8c31-f8b8-4e9c-a044-b7439e0d817f.png)

![image](https://user-images.githubusercontent.com/64946271/215339651-2adef3bd-b2a5-4fef-bbd0-5e30346498aa.png)
прогони тесты локально

2023-01-30 11:47 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/fstk1337/1675079268/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/fstk1337/1675079268/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/fstk1337/1675079268/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/fstk1337/1675079268/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/fstk1337/1675079268/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/fstk1337/1675079268/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/fstk1337/1675079268/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/fstk1337/1675079268/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/fstk1337/1675079268/content-window.png)

2023-01-30 11:49 UTC, fstk1337 commented on src/components/app-nav-categories/app-nav-categories.tsx
> +const categories = [
Согласен, сделано.

2023-01-30 11:49 UTC, fstk1337 commented on src/components/app-nav/app-nav.tsx
> +const navTabs = [
Готово.

2023-01-30 11:49 UTC, fstk1337 commented on src/components/book-list/book-list.tsx
> +const books = [
Готово.

2023-01-30 11:50 UTC, fstk1337 commented on src/components/book-main/book-main.tsx
> +const reviews = [
Готово.

2023-01-30 11:50 UTC, fstk1337 commented on src/pages/book/book-page.tsx
> +const books = [
Готово.

2023-01-30 11:50 UTC, fstk1337 commented on src/pages/public-offer/public-offer-content.tsx
> +export function PublicOfferContent() {
Сделано.

2023-01-30 11:50 UTC, fstk1337 commented on src/pages/book/book-page.tsx
> +import { useParams } from 'react-router-dom';
Сделано.

2023-01-30 11:54 UTC, dariavorom requested changes

2023-01-30 11:54 UTC, dariavorom commented on src/components/book-card/book-card.tsx
> +import { FC } from 'react';
молодец! осталось только поправить верстку в карточке 
нужно, чтобы кнопка бронирования с рейтингом находидись на одном уровне во всех карточках
![image](https://user-images.githubusercontent.com/64946271/215469946-0943c6ea-4eeb-4865-baea-0f4c02e03c0c.png)

2023-01-30 12:01 UTC, fstk1337 commented on src/components/book-card/book-card.tsx
> +import { FC } from 'react';
Я прошу прощения, просто в макете везде положение разное относительно низа карточки. Там фиксированные отступы сверху вниз, поэтому в случае короткого названия книги всё съезжает. Специально так делал.
Переделать?

2023-01-30 14:54 UTC, dariavorom approved these changes

2023-01-30 14:56 UTC, dariavorom commented on src/components/book-card/book-card.tsx
> +import { FC } from 'react';
Ты прав) Тогда на твое усмотрение.

2023-01-31 07:53 UTC, merged